union _Entity = User #federation

scalar _Any #federation

scalar _FieldSet #federation

schema {
  query: Query
}

type Query @extends {
  _service: _Service #federation
  #  _entities: _Entity  #federation
  fetchUserById(id: ID!): User
}

type User @key(fields: "id") {
  id: ID!
  email: String
}

type _Service { #federation
  sdl: String!  #federation
}               #federation
