union _Entity = User | Product #federation

union ProductImageAsset = ImageDelegated | ImageInternal

scalar _Any #federation

scalar _FieldSet #federation

schema {
  query: Query
}

type Query @extends {
  _entities(representations: [_Any!]!): [_Entity] #federation
  # Note: this query should *not* return federation specific fields
  #(see resolver)
  _service: _Service! #federation
  product(id: ID!): Product
  getProducts: [Product]
}

type User @key(fields: "id") @extends {
  id: ID! @external
  products: [Product] @requires(fields: "id")
}

type Product @key(fields: "id") {
  id: ID!
  name: String
  brand: String
  priceUSD: Int
  image: ImageInternal
  images: [ProductImage]
}

type _Service { #federation
  sdl: String! #federation
} #federation

type ProductImage {
  caption: String
  asset: ProductImageAsset
}

interface ImageInterface @extends {
  url: String @external
  altText: String @external
}

type ImageInternal implements ImageInterface {
  url: String
  altText: String
}

type ImageDelegated @extends {
  id: ID! @external
}
